UFL 2025-01-19_07-16-36

diff --git a/DEBIAN/DEBIAN/preinst b/DEBIAN/DEBIAN/preinst
--- a/DEBIAN/DEBIAN/preinst
+++ b/DEBIAN/DEBIAN/preinst
@@ -1,4 +1,5 @@
 #!/usr/bin/bash
+set -e
 
 def_v="osiris2"
 
@@ -158,7 +159,7 @@ git clone --depth 1 --filter=blob:none --sparse "${repo_url}" "${temp_repo}" || 
 cd "${temp_repo}"
 git sparse-checkout set --no-cone "/${gitup_remote_inst}" || {
   echo "Error: No se pudo configurar sparse-checkout para ${gitup_remote_inst}" | tee -a "${install_log}"
-  echo '{"status": "error", "message": "Error en sparse-checkout para '.${gitup_remote_inst}.'}' > "${error_file}"
+  echo '{"status": "error", "message": "Error en sparse-checkout para '.${gitup_remote_inst}.'}" > "${error_file}"
   exit 1
 }
 
@@ -205,13 +206,11 @@ git clone --depth 1 --filter=blob:none --sparse "${repo_url}" "${temp_repo}" || 
 cd "${temp_repo}"
 
 download_fgit() { 
-
-
      local file_path=$1
      local install_log=$2
      local error_file=$3
      local MODE=$4
-     
+     local dest=$5
            # Verificar si el archivo existe en el repositorio
   echo "Intentando descargar ${file_path} desde el repositorio base..."
   # Si es directorio, usar git sparse-checkout con --cone
@@ -232,48 +231,32 @@ download_fgit() {
     }
   fi
 
-
     if [[ "${MODE}" == "ForceUpgrade" ]]; then
-    
-    echo "-------------------------------------------------------------"
-    echo "¡Advertencia:! El archivo o directorio ${dest} ya existe.    "
-    echo "      ESTA USANDO EL MODO REINSTALL                          "
-    echo " - MODO FORCEUPGRADE                                         "
-    echo " → Se reescribirán los archivos a la última versión estable  "
-    echo "-------------------------------------------------------------"
-    echo "Sobrescribiendo ${dest}..."
-    echo 
-    echo 
-      cp "${file_path}" "${dest}" || {
+       echo "-------------------------------------------------------------"
+        echo "¡Advertencia:! El archivo o directorio ${dest} ya existe.    "
+        echo "      ESTA USANDO EL MODO REINSTALL                          "
+        echo " - MODO FORCEUPGRADE                                         "
+        echo " → Se reescribirán los archivos a la última versión estable  "
+        echo "-------------------------------------------------------------"
+        echo "Sobrescribiendo ${dest}..."
+        echo 
+        echo 
+       
+        cp "${file_path}" "${dest}" || {
         echo "Error: No se pudo sobrescribir ${file_path} a ${dest}" | tee -a "${install_log}"
         echo '{"status": "error", "message": "Error al mover archivo"}' > "${error_file}"
         # exit 1
       }
       echo "Archivo sobrescrito: ${file_path}" | tee -a "${install_log}"
-    elif [[ "${mode}" == "UPDATE" ]]; then
-
-
-    echo "-------------------------------------------------------------"
-    echo "¡Advertencia:! El archivo o directorio ${dest} ya existe.    "
-    echo "      ESTA USANDO EL MODO UPDATE                             "
-    echo " - MODO UPDATE                                               "
-    echo " → Se Moveran los archivos a su destino                      "
-    echo "-------------------------------------------------------------"
-
+    else
         mv -f "${file_path}" "${dest}" || {
         echo "Error: No se pudo sobrescribir ${file_path} a ${dest}" | tee -a "${install_log}"
         echo '{"status": "error", "message": "Error al mover archivo"}' > "${error_file}"
         exit 1
       }
        
-       
-       
-
-    else
-      echo "OBSERVAR MODOS"
-      echo "No se sobrescribió ${dest}. Continuando con la instalación."
+      echo "Archivo movido a : ${dest}" | tee -a "${install_log}"
     fi
-
 }
 
 # Procesar archivos listados en ${gitinstfn}
@@ -294,76 +277,23 @@ while IFS= read -r line; do
   echo "Procesando: ${file_path}"
   dest="${base}/${file_path}"
   if [ -e "${dest}" ]; then
-     
 
-   if [[ "$MODE" == "ForceUpgrade" ]]; then
-   
-      download_fgit "$file_path"  "$install_log" "$error_file" "$MODE"
- 
-     else
-       echo "######################################################" 
-       echo " Ya existe ${file_path}                               "
-       echo " Seleccione Modo FORCEUPGRADE                         "
-       echo " Para reescribir los Archivos Existentes              "
-       echo "######################################################"
-     fi
-
-   else
-  
-   download_fgit "$file_path"  "$install_log" "$error_file" "UPDATE"
-
-   fi
+      if [[ "$MODE" == "ForceUpgrade" ]]; then
+        download_fgit "$file_path"  "$install_log" "$error_file" "$MODE" "$dest"
+        else
+        echo "######################################################" 
+        echo " Ya existe ${file_path}                               "
+        echo " Seleccione Modo FORCEUPGRADE                         "
+        echo " Para reescribir los Archivos Existentes              "
+        echo "######################################################"
+        
+      fi
+    else
+    download_fgit "$file_path"  "$install_log" "$error_file" "UPDATE" "$dest"
+  fi
   
    continue
-   
 
-# Verificar si el archivo o directorio fue descargado
-if [ -e "${file_path}" ]; then
-  dest="${base}/${file_path}"
-  dir_path=$(dirname "${dest}")
-  mkdir -p "${dir_path}"
-
-  # Verificar si el archivo de destino ya existe
-  if [ -e "${dest}" ]; then
-    echo "---------------------------------------------------------"
-    echo "¡Advertencia:! El archivo o directorio ${dest} ya existe."
-    echo "      USE MODO REINSTALAR PARA SOBREESCRIBIRLOS          "
-    echo " - MODO INSTALL+   → Sólo se instalarán Archivos nuevos  "
-    echo "---------------------------------------------------------"
-    sleep 0.3 
-    # Preguntar si está en modo actualización 
-    answer=$FORCEUPGRADEMODE 
-    if [[ "${answer}" == "True" ]]; then
-      echo "Sobrescribiendo ${dest}..."
-    echo 
-    echo " #####$$$$$$######"
-    #  mv -f "${file_path}" "${dest}" || {
-     #   echo "Error: No se pudo sobrescribir ${file_path} a ${dest}" | tee -a "${install_log}"
-    #    echo '{"status": "error", "message": "Error al mover archivo"}' > "${error_file}"
-        # exit 1
-     # }
-
-      echo "Archivo sobrescrito: ${file_path}" | tee -a "${install_log}"
-    else
-      echo "No se sobrescribió ${dest}. Continuando con la instalación."
-    fi
-  else
-    # Si el archivo de destino no existe, mover sin preguntar
-    mv "${file_path}" "${dest}" || {
-      echo "Error: No se pudo mover ${file_path} a ${dest}" | tee -a "${install_log}"
-      echo '{"status": "error", "message": "Error al mover archivo"}' > "${error_file}"
-      # exit 1
-    }
-    echo "Archivo descargado: ${file_path}" | tee -a "${install_log}"
-  fi
-else
-  echo "Error: ${file_path} no se encuentra en el repositorio" | tee -a "${install_log}"
-  echo '{"status": "error", "message": "'${file_path}' no encontrado en repositorio"}' > "${error_file}"
-  echo "\n\n ----->  \n  error remoto !!!  \n\n"
-  # sleep 3
-  # exit 1
-fi
-  
 done < "${gitup_file}"
 
 # Limpiar directorio temporal
@@ -405,4 +335,3 @@ else
     echo "Finalizando Tareas...."
     exit 0
 fi
-
